language: r
cache: packages

warnings_are_errors: false

env:
 global:
   - CRAN: http://cran.rstudio.com

after_success:
  - Rscript -e 'install.packages("covr", repos="http://cran.rstudio.com")'
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
