language: r
cache: packages

r:
  - oldrel
  - release
  - devel

warnings_are_errors: true

env:
 global:
   - CRAN: http://cran.rstudio.com

r_binary_packages:
  - dplyr
  - dbplyr
  - LaF
  - testthat
  - rlang

after_success:
  - Rscript -e 'install.packages("covr", repos="http://cran.rstudio.com")'
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
